server/app/mod_msg/controllers.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from peewee import IntegrityError

from app.models import User, DATABASE, Message
from app.utils import get_current_user, login_required
from app.mod_msg.forms import MessageForm


mod_msg = Blueprint('messages', __name__, url_prefix='/message')


@mod_msg.route('/to/<username>', methods=['GET'])
@login_required
def message_to(username):
    form = MessageForm(request.form)
    user = User.get(User.username == username)
    messages = get_current_user().get_messages_with_user(user)
    return render_template('msg/chat_page.html', messages=messages, to_user=user, form=form)


@mod_msg.route('/to/<username>/send', methods=['POST'])
@login_required
def send_message_to(username):
    form = MessageForm(request.form)
    user = User.get(User.username == username)
    if form.validate():
        try:
            with DATABASE.atomic():
                print(Message.create(from_user=get_current_user(),
                                     to_user=user,
                                     content=request.form.get('content')))
        except IntegrityError:
            flash('something went wrong')
    return redirect(request.referrer)

server/app/mod_user/controllers.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask.views import MethodView
from peewee import IntegrityError


from app.models import User, Post, DATABASE, Follow
from app.utils import get_current_user, login_required
from app.mod_user.forms import PostForm

mod_user = Blueprint('users', __name__, url_prefix='/users')


class UserPage(MethodView):
    def get(self, username):
        form = PostForm()
        user = User.get(User.username == username)
        if user is None:
            return redirect(url_for('main.feed'))
        return render_template('user/user_page.html', user=user, form=form)

    def post(self, username):
        form = PostForm()
        user = User.get(User.username == username)
        Post.create(user=get_current_user(),
                    content=request.form.get('content'))
        return render_template('user/user_page.html', user=user, form=form)


@mod_user.route('/<username>/following', methods=['GET'])
@login_required
def following(username):
    user = User.get(User.username == username)
    if user is None:
        return redirect(url_for('main.feed'))
    return render_template('user/follow_page.html', page_type='following', user_list=user.get_following())


@mod_user.route('/<username>/followers', methods=['GET'])
@login_required
def followers(username):
    user = User.get(User.username == username)
    if user is None:
        return redirect(url_for('main.feed'))
    return render_template('user/follow_page.html', page_type='followers', user_list=user.get_followers())


@mod_user.route('/<username>/follow', methods=['POST'])
@login_required
def follow(username):
    user = User.get(User.username == username)
    if user is None:
        return redirect('main.feed')
    try:
        with DATABASE.atomic():
            Follow.create(from_user=get_current_user(), to_user=user)
    except IntegrityError:
        pass
    return redirect(url_for('users.user_page', username=user.username))


@mod_user.route('/<username>/unfollow', methods=['POST'])
@login_required
def unfollow(username):
    user = User.get(User.username == username)
    if user is None:
        return redirect('main.feed')
    Follow.delete().where((Follow.from_user == get_current_user())
                          & (Follow.to_user == user)).execute()
    return redirect(url_for('users.user_page', username=user.username))


mod_user.add_url_rule('/<username>', view_func=UserPage.as_view('user_page'), methods=['GET', 'POST'])

server/app/templates/user/follow_page.html
{% extends 'base.html' %}
{% block header %}
    {% block title %} {{ page_type }} {% endblock %}
{% endblock %}
{% block content %}
    {% for user in user_list %}
        <li>{% include 'includes/follow.html' %}</li>
    {% endfor %}
{% endblock %}

server/app/templates/user/user_page.html
{% extends 'base.html' %}
{% block header %}
    {% block title %}{{ user.first_name }} {{ user.last_name }}{% endblock %}
{% endblock %}
{% block content %}
    <a href="{{ url_for('users.followers', username=user.username, page_type='followers', user_list=user.get_followers())}}">followers</a>
    <a href="{{ url_for('users.following', username=user.username, page_type='following', user_list=user.get_following()) }}">following</a>
    {% if user == current_user %}
    <div>
        <form action="{{ url_for('users.user_page', username=user.username) }}" method="post">
            {{ form.content.label }}    {{ form.content(size=20) }}
            <input value="Post" type="submit">
        </form>
    </div>
    {% else %}
        {% if current_user|is_following(user) %}
            <form action="{{ url_for('users.unfollow', username=user.username) }}" method="post">
                <input type="submit" value="unfollow">
            </form>
        {% else %}
            <form action="{{ url_for('users.follow', username=user.username) }}" method="post">
                <input type="submit" value="follow">
            </form>
        {% endif %}
        <a href="{{ url_for('messages.message_to', username=user.username, messages=current_user.get_messages_with_user(user))  }}">Message this User</a>
    {% endif %}

    {% for post in user.get_posts() %}
        <div>
            {% include 'includes/post.html' %}
        </div>
    {% endfor %}
{% endblock %}